apiVersion: v1
data:
  index.html: |-
    <h1>Kubernetes Security Assessment</h1>
    <h3>Current security level: <span style="color: {{ .Values.info.color }}">{{ .Values.info.securityLevel }}</span></h3>
    <br/>
    <h2>Security reports:</h2>
    <ul>
    <li><a href="./kube-hunter.txt">Kube-hunter</a></li>
    </ul>
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace.name }}
