apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kubescape
  name: kubescape-discovery
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubescape-discovery-clusterroles
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "describe"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubescape-discovery-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubescape-discovery-clusterroles
subjects:
- kind: ServiceAccount
  name: kubescape-discovery
  namespace: {{ .Release.Namespace }}
---
{{- if .Values.kubescape.deploy }}
apiVersion: batch/v1
kind: Job
metadata:
  name: kubescape
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: kubescape
    spec:
      serviceAccountName: kubescape-discovery
      restartPolicy: OnFailure
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kubescape
          image: {{ .Values.kubescape.image }}
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              kubescape scan --format json
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.kubescape.storage.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kubescape.storage.size }}
