apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    pod-security.kubernetes.io/enforce: {{ .Values.namespace.labels.enforce }}
    pod-security.kubernetes.io/enforce-version: {{ .Values.namespace.labels.enforceVersion }}