apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksa-parser
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: ksa-parser
  template:
    metadata:
      name: ksa-parser
      labels:
        app: ksa-parser
    spec:
      containers:
      - image: {{ .Values.parser.image }}
        imagePullPolicy: IfNotPresent
        name: ksa-parser
        envFrom:
        - configMapRef:
            name: {{ .Values.database.cm.name }}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.secret.name }}
              key: POSTGRES_PASSWORD
        - name: PORT
          value: "{{ .Values.parser.service.targetPort }}"
        - name: REPORT_DATA_LOCATION
          value: {{ .Values.parser.volumes.basepath }}
        volumeMounts:
        - name:  {{ .Values.trivy.storage.name }}
          mountPath: {{ .Values.parser.volumes.trivy.path }}
          readOnly: true
        - name: {{ .Values.kubebench.storage.name }}
          mountPath: {{ .Values.parser.volumes.kubebench.path }}
          readOnly: true
        - name: {{ .Values.prowler.storage.name }}
          mountPath: {{ .Values.parser.volumes.prowler.path }}
          readOnly: true
        - name: {{ .Values.kubescape.storage.name }}
          mountPath: {{ .Values.parser.volumes.kubescape.path }}
          readOnly: true
      volumes:
      - name: {{ .Values.trivy.storage.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.trivy.storage.name }}
      - name: {{ .Values.kubebench.storage.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.kubebench.storage.name }}
      - name: {{ .Values.prowler.storage.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.prowler.storage.name }}
      - name: {{ .Values.kubescape.storage.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.kubescape.storage.name }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.parser.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.parser.service.type }}
  ports:
  - port: {{ .Values.parser.service.port }}
    protocol: TCP
    targetPort: {{ .Values.parser.service.targetPort }}
  selector:
    app: ksa-parser
