apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.sts.name }}
  labels:
    app: {{ .Values.database.sts.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.database.sts.name }}
  serviceName: {{ .Values.database.service.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.database.sts.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.database.sts.name }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.secret.name }}
                  key: password
            - name: POSTGRES_DB
              value: "demo"
            - name: PGUSER
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.database.sts.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.database.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.database.sts.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.database.sts.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.database.sts.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.database.sts.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.service.name }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: {{ .Values.database.sts.name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

