info:
  securityLevel: baseline
  color: orange

trivy:
  image: aquasec/trivy:latest
  init:
    image: alpine/k8s@sha256:fea4057e9e8a0d363ac4f67e55cf6ab8a6e44a057e0e0315ca7b5068927c5fdc
  storage:
    name: trivy-scan-results
    size: 200Mi

kubebench:
  image: docker.io/aquasec/kube-bench:v0.9.3
  storage:
    name: kube-bench-scan-results
    size: 200Mi

deployment:
  busybox:
    image: busybox:latest
  httpd:
    image: httpd:latest
  security:
    default: true
    runAsUser:
    allowPrivilegeEscalation:
    capabilities:
      add:
      drop:
    runAsNonRoot:
    seccompProfileType:

service:
  name: ksa-svc
  type: LoadBalancer
  port: 8888
  targetPort: 80

ingress:
  enabled: false

configmap:
  name: public-html-cm