trivy:
  deploy: false
  image: aquasec/trivy:latest
  init:
    image: alpine/k8s@sha256:fea4057e9e8a0d363ac4f67e55cf6ab8a6e44a057e0e0315ca7b5068927c5fdc
  storage:
    name: trivy-scan-results
    size: 200Mi

kubebench:
  deploy: false
  image: docker.io/aquasec/kube-bench:v0.9.3
  storage:
    name: kube-bench-scan-results
    size: 200Mi

dashboard:
  image: ksa/dashboard:latest
  security:
    default: true
    runAsUser:
    allowPrivilegeEscalation:
    capabilities:
      add:
      drop:
    runAsNonRoot:
    seccompProfileType:
  service:
    name: dashboard
    type: LoadBalancer
    port: 3123
    targetPort: 3000

parser:
  image: ksa/parser:latest
  service:
    name: parser
    type: LoadBalancer
    port: 8123
    targetPort: 8000
  volumes:
    trivy:
      name: trivy-data
      path: /opt/trivy-data
    kubebench:
      name: kubebench-data
      path: /opt/kubebench-data

aggregator:
  image: ksa/aggregator:latest
  service:
    name: aggregator
    type: LoadBalancer
    port: 8124
    targetPort: 8000