apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.configMap.name }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
data:
  spring.datasource.url: jdbc:postgresql://postgres:5432/demo
  spring.datasource.username: postgres