{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demo.serviceAccountName" . }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "demo.serviceAccountName" . }}-rolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "demo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  # 1.1. Misconfigured RBAC
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
